services:
  api:
    build: .
    container_name: app-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=app_db
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev
    develop:
      watch:
      - action: sync
        path: ./src
        target: /src
        ignore:
          - node_modules/
      - action: rebuild
        path: package.json

  db:
    image: postgres
    container_name: app-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data

volumes:
  app-db-data:
